// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_feeds_users_join_on_id.sql

package database

import (
	"context"
)

const getFeedsWithUser = `-- name: GetFeedsWithUser :many
SELECT users.name AS user_name, 
feeds.name AS feed_name, 
feeds.url as feed_url 
FROM feeds 
INNER JOIN users 
ON feeds.user_id = users.id
`

type GetFeedsWithUserRow struct {
	UserName string
	FeedName string
	FeedUrl  string
}

func (q *Queries) GetFeedsWithUser(ctx context.Context) ([]GetFeedsWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsWithUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsWithUserRow
	for rows.Next() {
		var i GetFeedsWithUserRow
		if err := rows.Scan(&i.UserName, &i.FeedName, &i.FeedUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
